In [4]:
import numpy as np
from pprint import pprint

In [2]:
out = np.random.randint(0, 10, 50)

In [3]:
out

array([5, 8, 7, 6, 5, 6, 9, 2, 8, 6, 4, 0, 6, 2, 1, 1, 0, 8, 4, 9, 9, 4,
       3, 0, 7, 3, 8, 4, 6, 3, 4, 5, 7, 8, 0, 2, 7, 0, 0, 0, 0, 8, 2, 9,
       9, 5, 4, 6, 1, 3])

In [15]:
chunk = 3
c_val_lst = [out[i:i+chunk] for i in range(0, len(out), chunk)]

In [16]:
pprint(c_val_lst)

[array([5, 8, 7]),
 array([6, 5, 6]),
 array([9, 2, 8]),
 array([6, 4, 0]),
 array([6, 2, 1]),
 array([1, 0, 8]),
 array([4, 9, 9]),
 array([4, 3, 0]),
 array([7, 3, 8]),
 array([4, 6, 3]),
 array([4, 5, 7]),
 array([8, 0, 2]),
 array([7, 0, 0]),
 array([0, 0, 8]),
 array([2, 9, 9]),
 array([5, 4, 6]),
 array([1, 3])]
